Repository OpenCircuits/OpenCircuits, pull requests merged in 2021-11, with the labels that each got.

#807 Reducing the number of ports can cause an error.
  src/site/shared/containers/SelectionPopup/modules/Module.tsx
Labels: hacktoberfest-accepted

#806 Undo errors
  src/app/digital/actions/ports/CoderPortChangeAction.ts
  src/site/pages/digital/src/containers/SelectionPopup/modules/SegmentCountModule.tsx
Labels: hacktoberfest-accepted

#840 Added Documentation instructions
  docs/GettingStarted/Running.md
Labels: Area: Documentation

#823 Unit tests for deleting wires and objects
  src/app/tests/digital/utils/tools/InteractionTool.test.ts
Labels: hacktoberfest-accepted

#790 Item Nav Drag Preview
  src/app/core/utils/Input.ts
  src/site/pages/digital/src/containers/DigitalItemNav/index.tsx
  src/site/pages/digital/src/containers/MainDesigner/index.tsx
  src/site/pages/digital/src/utils/Constants.ts
  src/site/pages/digital/src/utils/DigitalCreate.ts
  src/site/shared/components/DragDroppable/Draggable.tsx
  src/site/shared/containers/ItemNav/index.scss
  src/site/shared/containers/ItemNav/index.tsx
  src/site/shared/utils/hooks/useDocEvent.ts
  src/site/shared/utils/hooks/useKey.ts
  src/site/shared/utils/hooks/useKeyDownEvent.ts
  src/site/shared/utils/hooks/useMousePos.ts
Labels: hacktoberfest-accepted

#824 Addition action docs
  src/app/core/actions/addition/AddGroupActionFactory.ts
  src/app/core/actions/addition/ConnectionAction.ts
  src/app/core/actions/addition/PlaceAction.ts
  src/app/core/actions/addition/SplitWireAction.ts
Labels: hacktoberfest-accepted, Area: Documentation

#813 Fixed issue 774
  src/app/core/actions/addition/SplitWireAction.ts
Labels: hacktoberfest-accepted

#830 Documentation for IOObject Renderers
  src/app/digital/rendering/ioobjects/ComponentRenderer.ts
  src/app/digital/rendering/ioobjects/IOLabelRenderer.ts
  src/app/digital/rendering/ioobjects/IOPortRenderer.ts
  src/app/digital/rendering/ioobjects/WireRenderer.ts
Labels: hacktoberfest-accepted, Area: Documentation

#826 Fix issue 746
  src/app/core/tools/handlers/CopyHandler.ts
  src/app/core/tools/handlers/PasteHandler.ts
Labels: hacktoberfest-accepted

#832 Added items to Quick Start PopUp
  src/site/pages/digital/src/containers/QuickStartPopup/index.tsx
  src/site/shared/components/Popup/index.scss
Labels: hacktoberfest-accepted

#821 fixed wonky wire connections (issue 610)
  src/app/core/tools/WiringTool.ts
Labels: hacktoberfest-accepted

#828 Documentation for Shapes
  src/app/core/rendering/shapes/ArcCircle.ts
  src/app/core/rendering/shapes/Circle.ts
  src/app/core/rendering/shapes/Curve.ts
  src/app/core/rendering/shapes/Line.ts
  src/app/core/rendering/shapes/Polygon.ts
  src/app/core/rendering/shapes/QuadCurve.ts
  src/app/core/rendering/shapes/Rectangle.ts
  src/app/core/rendering/shapes/Shape.ts
Labels: hacktoberfest-accepted, Area: Documentation

#801 switched from keycode to key (issue #789)
  src/app/core/utils/Constants.ts
  src/app/core/utils/Events.ts
  src/app/core/utils/Input.ts
  src/app/core/utils/KeyboardListener.ts
  src/app/tests/helpers/FakeInput.ts
  src/site/shared/utils/hooks/useKeyDownEvent.ts
Labels: hacktoberfest-accepted

#787 More debug options
  src/app/core/rendering/DebugRenderer.ts
  src/app/core/utils/CircuitInfo.ts
  src/app/tests/helpers/Setup.ts
  src/site/pages/digital/src/containers/App/index.tsx
  src/site/pages/digital/src/state/reducers.ts
  src/site/pages/digital/src/utils/CircuitInfo/CreateInfo.ts
  src/site/shared/components/SwitchToggle/index.scss
  src/site/shared/components/SwitchToggle/index.tsx
  src/site/shared/containers/Header/Right/SettingsMenu/AutoSaveToggle.tsx
  src/site/shared/containers/Header/Right/SettingsMenu/index.scss
  src/site/shared/containers/Header/Right/SettingsMenu/index.tsx
  src/site/shared/containers/Header/Right/index.tsx
  src/site/shared/containers/Header/index.tsx
  src/site/shared/state/DebugInfo.ts
  src/site/shared/state/actions.ts
  src/site/shared/state/index.ts
Labels: hacktoberfest-accepted

#805 fixed context menu issue #714
  src/site/shared/containers/ContextMenu/index.tsx
Labels: hacktoberfest-accepted

#880 Adding comment to Clock.ts
  src/app/digital/models/ioobjects/inputs/Clock.ts
Labels: Area: Documentation

#867 Documentation update for ClampedValue.ts
  src/app/core/utils/math/ClampedValue.ts
Labels: Area: Documentation

#793 Allow ICs to be deleted from ItemNav
  src/app/digital/actions/DeleteICDataAction.ts
  src/site/pages/digital/src/containers/DigitalItemNav/index.tsx
  src/site/shared/containers/ItemNav/index.scss
  src/site/shared/containers/ItemNav/index.tsx
Labels: hacktoberfest-accepted

#819 Power Wires During Creation
  src/app/digital/rendering/ioobjects/WireRenderer.ts
Labels: hacktoberfest-accepted

#794 JPEG Download
  src/site/pages/digital/src/utils/CircuitInfo/DigitalCircuitInfoHelpers.ts
  src/site/shared/containers/Header/Right/DownloadMenuDropdown.tsx
  src/site/shared/utils/CircuitInfoHelpers.ts
  src/site/shared/utils/ImageExporter.ts
Labels: hacktoberfest-accepted
