Repository OpenCircuits/OpenCircuits, pull requests merged in 2022-07, with the labels that each got.

#1071 yarn start now defaults to Digital
  scripts/start.ts
Labels: Status: Ready to Merge, Area: DevOps

#1078 Eslint fix sonarjs
  linting/.sonarjs.cjs
  scripts/docs/display.ts
  src/app/core/utils/math/MathUtils.ts
  src/app/digital/models/ioobjects/latches/DLatch.ts
  src/app/digital/models/ioobjects/other/ICData.ts
  src/app/tests/digital/utils/tools/InteractionTool.test.ts
  src/site/pages/digital/src/containers/SelectionPopup/modules/OscilloscopeModules.tsx
Labels: Area: DevOps, Status: Awaiting Review

#1052 Label automation
  .github/workflows/labelPR.yml
  .github/workflows/labelReview.yml
Labels: Area: DevOps, Status: Awaiting Review

#1080 Eslint fix jsxa11y
  linting/.jsxa11y.cjs
  src/site/pages/analog/src/containers/ImageExporterPreview/index.tsx
  src/site/pages/digital/src/containers/DigitalItemNav/index.tsx
  src/site/pages/digital/src/containers/ImageExporterPreview/index.tsx
  src/site/pages/landing/src/App/index.scss
  src/site/pages/landing/src/Footer/index.tsx
  src/site/pages/landing/src/Header/index.tsx
  src/site/pages/landing/src/Main/index.tsx
  src/site/shared/components/ButtonToggle/index.tsx
  src/site/shared/components/CircuitPreview/index.tsx
  src/site/shared/components/Overlay/index.tsx
  src/site/shared/components/SwitchToggle/index.tsx
  src/site/shared/containers/Header/Left/HistoryToggleButton.tsx
  src/site/shared/containers/Header/Right/DownloadMenuDropdown.tsx
  src/site/shared/containers/Header/Right/TutorialDropdown.tsx
  src/site/shared/containers/Header/Right/UtilitiesDropdown.tsx
  src/site/shared/containers/HistoryBox/index.tsx
  src/site/shared/containers/ItemNav/index.tsx
Labels: Area: DevOps

#1081 Added linting to CI tests
  .github/workflows/ci_tests.yml
Labels: Area: DevOps
