Repository OpenCircuits/OpenCircuits, pull requests merged in 2022-06, with the labels that each got.

#958 Add more eslint rules
  .eslintrc.js
  docs/GettingStarted/Contributing.md
  docs/GettingStarted/Running.md
  linting/.core.js
  linting/.custom.js
  linting/.imports.js
  linting/.jestRules.js
  linting/.jsdoc.js
  linting/.jsxa11y.js
  linting/.react.js
  linting/.sonarjs.js
  linting/.sortDestructureKeys.js
  linting/.ts.js
  linting/.unicorn.js
  package.json
  src/site/shared/components/InputField/index.tsx
  yarn.lock
Labels: Status: Awaiting Review

#1016 Make History Box Draggable/Resizable
  src/app/analog/tools/handlers/CursorHandler.ts
  src/app/core/utils/math/Rect.ts
  src/site/pages/digital/public/img/icons/resizer.svg
  src/site/shared/components/AdjustableElement/index.scss
  src/site/shared/components/AdjustableElement/index.tsx
  src/site/shared/components/AdjustableElement/useAdjustableElement.ts
  src/site/shared/containers/HistoryBox/index.scss
  src/site/shared/containers/HistoryBox/index.tsx
  src/site/shared/utils/hooks/useMousePos.ts
Labels: Status: Ready to Merge

#1022 Fixed Wire Delete for issue 902
  src/app/core/actions/addition/SplitWireAction.ts
  src/app/core/actions/deletion/DeleteGroupActionFactory.ts
  src/app/core/actions/ports/PortChangeAction.ts
  src/app/core/tools/handlers/DeleteHandler.ts
  src/app/core/tools/handlers/SelectPathHandler.ts
  src/app/core/utils/ComponentUtils.ts
  src/app/tests/digital/models/CircuitDesigner.test.ts
  src/app/tests/digital/models/ioobjects/inputs/Button.test.ts
  src/app/tests/digital/models/ioobjects/inputs/Clock.test.ts
  src/app/tests/digital/models/ioobjects/inputs/ConstantHigh.test.ts
  src/app/tests/digital/models/ioobjects/inputs/ConstantLow.test.ts
  src/app/tests/digital/models/ioobjects/other/Comparator.test.ts
  src/app/tests/digital/models/ioobjects/other/IC.test.ts
  src/app/tests/digital/utils/Simplifications.test.ts
  src/app/tests/digital/utils/actions/CreateICDataAction.test.ts
  src/app/tests/digital/utils/actions/DeleteGroupAction.test.ts
  src/app/tests/digital/utils/actions/InputPortChangeAction.test.ts
  src/app/tests/digital/utils/actions/MuxSelectPortChangeAction.test.ts
  src/app/tests/digital/utils/actions/SnipGateAction.test.ts
  src/app/tests/digital/utils/actions/SplitWireAction.test.ts
  src/app/tests/digital/utils/tools/InteractionTool.test.ts
  src/app/tests/digital/utils/tools/TranslateTool.test.ts
  src/app/tests/helpers/Extensions.ts
  src/app/tests/helpers/Helpers.ts
Labels: Status: Ready to Merge

#1033 Changed how moving groups of compenents works
  src/site/pages/digital/src/containers/App/index.tsx
  src/site/pages/digital/src/containers/SelectionPopup/modules/ClockSyncButtonModule.tsx
  src/site/shared/components/InputField/index.scss
  src/site/shared/components/InputField/index.tsx
  src/site/shared/containers/SelectionPopup/index.scss
  src/site/shared/containers/SelectionPopup/modules/PositionModule.tsx
  src/site/shared/containers/SelectionPopup/modules/inputs/ModuleInputField.tsx
  src/site/shared/containers/SelectionPopup/modules/inputs/NumberModuleInputField.tsx
Labels: Status: Ready to Merge

#1060 Update Introduction.md
  docs/Introduction.md
Labels: Status: Ready to Merge

#983 Standardized breakpoint location
  package.json
  scripts/webpack/config/css.js
  src/react-app-env.d.ts
  src/site/pages/analog/tsconfig.json
  src/site/pages/digital/tsconfig.json
  src/site/shared/components/InputField/index.scss
  src/site/shared/containers/HistoryBox/index.scss
  src/site/shared/containers/ItemNav/index.scss
  src/site/shared/containers/ItemNav/index.tsx
  src/site/shared/utils/_constants.scss
  yarn.lock
Labels: Area: Frontend, Status: Ready to Merge

#908 Added Replace Component Design Doc
  docs/Other/DesignDocs/Replace Component.md
  docs/Other/DesignDocs/_timeline.jsx
  docs/Other/DesignDocs/img/ReplaceComponent/ReplaceComponentIdea.jpg
Labels: Area: Documentation

#938 Circuit to Expression Design Doc
  docs/Other/DesignDocs/CircuitToExpression.md
  docs/Other/DesignDocs/ExpressionToCircuit.md
  docs/Other/DesignDocs/Replace Component.md
  docs/Other/DesignDocs/img/CircuitToExpression/MockupPart1.jpg
  docs/Other/DesignDocs/img/CircuitToExpression/MockupPart2.jpg
  docs/Other/DesignDocs/img/CircuitToExpression/MockupPart3.jpg
Labels: Area: Documentation
