Repository OpenCircuits/OpenCircuits, pull requests merged in 2023-02, with the labels that each got.

#1222 Closed loop for CircuitLog event clock
  src/app/core/internal/impl/CircuitLog.ts
Labels: Status: Awaiting Review

#1226 Implemented selectionsMidpoint function and tests
  src/app/core/public/api/Circuit.ts
  src/app/core/public/api/impl/BaseObject.ts
  src/app/core/public/api/impl/Circuit.ts
  src/app/tests/SelectionsMidpoint.test.ts
Labels: Status: Ready to Merge

#1227 Changed Examples
  src/site/pages/analog/public/examples/example1new.circuit
  src/site/pages/analog/public/examples/example3new.circuit
  src/site/pages/analog/public/img/thumbnails/example1new.png
  src/site/pages/analog/public/img/thumbnails/example3new.png
  src/site/pages/analog/src/data/examples.json
Labels: Analog

#1224 Error propagation proposal / integration.
  src/app/core/internal/impl/CircuitInternal.ts
  src/app/core/internal/impl/CircuitOps.ts
  src/app/core/internal/impl/ComponentInfo.ts
  src/app/core/public/api/impl/BaseObject.ts
  src/app/core/public/api/impl/Circuit.ts
  src/app/core/public/api/impl/Component.ts
  src/app/core/public/api/impl/Port.ts
  src/app/core/public/api/impl/Wire.ts
  src/app/core/utils/MultiError.ts
  src/app/core/utils/Result.ts
  src/app/digital/internal/DigitalComponents.ts
Labels: Status: Awaiting Review
