Repository OpenCircuits/OpenCircuits, pull requests merged in 2024-02, with the labels that each got.

#1114 Add eslint cache
  .gitignore
  package.json
  src/app/core/tools/WiringTool.ts
  src/site/pages/digital/src/utils/DigitalCreate.ts
Labels: Status: Ready to Merge

#1115 Lint only changed files
  .github/workflows/ci_tests.yml
  package.json
  scripts/lint.ts
  yarn.lock
Labels: Status: Changes Requested

#1238 Model refactor api expr to circ
  linting/.imports.cjs
  package.json
  src/app/core/public/api/Circuit.ts
  src/app/core/public/api/impl/Circuit.ts
  src/app/core/utils/CircuitUtils.ts
  src/app/core/utils/StringUtils.ts
  src/app/core/utils/math/Graph.ts
  src/app/tests/Extensions.ts
  src/app/tests/FirstAvailable.test.ts
  src/app/tests/PlaceComponentAt.test.ts
  src/app/tests/SelectionsMidpoint.test.ts
  src/site/pages/digital/src/containers/ExprToCircuitPopup/CustomOps.tsx
  src/site/pages/digital/src/containers/ExprToCircuitPopup/generate.ts
  src/site/pages/digital/src/containers/ExprToCircuitPopup/index.tsx
  src/site/pages/digital/src/utils/ExpressionParser/Constants/DataStructures.ts
  src/site/pages/digital/src/utils/ExpressionParser/Constants/Formats.ts
  src/site/pages/digital/src/utils/ExpressionParser/GenerateInputTree.ts
  src/site/pages/digital/src/utils/ExpressionParser/GenerateTokens.ts
  src/site/pages/digital/src/utils/ExpressionParser/TreeToCircuit.ts
  src/site/pages/digital/src/utils/ExpressionParser/index.ts
  src/site/pages/digital/tests/containers/ExprToCircuitPopup.test.tsx
  src/site/pages/digital/tests/utils/ExpressionParser.test.ts
  src/site/pages/digital/tsconfig.json
  yarn.lock
Labels: Status: Changes Requested

#1174 Add Playwright E2E Testing
  .github/workflows/playwright.yml
  .gitignore
  docs/GettingStarted/Running.md
  docs/Guides/Playwright.md
  linting/.jestRules.cjs
  linting/.playwright.cjs
  linting/.sonarjs.cjs
  linting/.ts.cjs
  package.json
  playwright.config.ts
  playwright/config/base.config.ts
  playwright/config/ci.config.ts
  playwright/config/digital.config.ts
  playwright/config/landing.config.ts
  playwright/landing/shared/basicLanding.spec.ts
  scripts/build.ts
  scripts/start.ts
  scripts/webpack/index.ts
  src/site/pages/landing/package.json
  yarn.lock
Labels: Status: Ready to Merge

#1284 Model refactor API SelectionPopup [1]
  src/app/core/internal/impl/CircuitInternal.ts
  src/app/core/internal/view/CircuitView.ts
  src/app/core/public/api/Camera.ts
  src/app/core/public/api/Circuit.ts
  src/app/core/public/api/Observable.ts
  src/app/core/public/api/Selections.ts
  src/app/core/public/api/impl/Camera.ts
  src/app/core/public/api/impl/Circuit.ts
  src/app/core/public/api/impl/Observable.ts
  src/app/core/public/api/impl/Selections.ts
  src/site/pages/digital/src/containers/App/index.tsx
  src/site/shared/circuitdesigner/CircuitDesigner.ts
  src/site/shared/containers/SelectionPopup/index.tsx
  src/site/shared/tools/PanTool.ts
Labels: Status: Awaiting Review

#1287 Model refactor API SideNav + ContextMenu
  src/site/pages/digital/src/containers/App/index.tsx
  src/site/pages/digital/src/index.tsx
  src/site/shared/containers/ContextMenu/index.tsx
  src/site/shared/containers/SideNav/index.tsx
  src/site/shared/tools/SelectionBoxTool.ts
  src/site/shared/tools/handlers/CleanupHandler.ts
  src/site/shared/tools/handlers/DuplicateHandler.ts
  src/site/shared/tools/handlers/FitToScreenHandler.ts
  src/site/shared/tools/handlers/PasteHandler.ts
Labels: Status: Awaiting Review
